
services:
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [
      "CMD-SHELL",
      "pg_isready -U postgres && \
        psql -U postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='boris_bb'\" | grep -q 1 && \
        psql -U postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='boris_nrw'\" | grep -q 1 && \
        psql -U postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='umgebungslaerm_bb'\" | grep -q 1"
      ]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  importer:
    build: ./importer
    container_name: boris_importer
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: pg
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
    volumes:
      - ./data:/data
      - ./importer:/importer
      - ./products:/products

  mapserver:
    build: ./mapserver
    container_name: mapserver
    depends_on:
      - db
      - importer
    ports:
      - "8081:80"

volumes:
  db_data:
